-- bscwave-gen-ports: derive a typed port record from a bsc-generated .cxx.
--
-- Reads <model>.cxx, finds the init_symbol(...) table and the constructor
-- initializer list, and emits a Haskell module with `Inputs`/`Outputs`
-- higher-kinded records plus their `Interface` instances.
--
-- Convention:
--   SYM_PORT  -> input  (any bsc port; an Action method `foo` contributes EN_foo)
--   SYM_MODULE -> output (a Reg; width pulled from the constructor call
--                          INST_<name>(simHdl, "<name>", this, <W>u, ...))
--   SYM_DEF   -> skipped (intermediate signals like WILL_FIRE_*)
--
-- Usage: bscwave-gen-ports <model>.cxx [-o Out.hs]
module Main where

import qualified Data.Char as Char
import qualified Data.List as List
import qualified Data.Map.Strict as Map
import System.Environment (getArgs)
import System.Exit (die)
import System.FilePath (takeBaseName)
import System.IO (IOMode (WriteMode), hPutStr, withFile, stdout)

data Sym = SymPort String Int | SymModule String Int deriving (Show)

-- | Parse `INST_<name>(simHdl, "<name>", this, <W>u, ...)` to recover register
-- widths. Returns a map from instance name to bit width.
parseInsts :: [String] -> Map.Map String Int
parseInsts = Map.fromList . concatMap go
  where
    go ln
      | Just rest <- List.stripPrefix "INST_" (dropWhile Char.isSpace ln)
      , (instName, '(':after) <- span (/= '(') rest
      , let parts = splitArgs after
      , length parts >= 4
      , let w = readWidth (parts !! 3)
      , w > 0
      = [(instName, w)]
      | otherwise = []

-- | Split a comma-separated arg list (up to the closing paren), respecting
-- a single level of nested parens.
splitArgs :: String -> [String]
splitArgs s = go 0 [] s
  where
    go _ acc [] = [reverse acc]
    go 0 acc (',':rest) = reverse acc : go 0 [] (dropWhile Char.isSpace rest)
    go 0 acc (')':_)    = [reverse acc]
    go n acc ('(':rest) = go (n+1) ('(':acc) rest
    go n acc (')':rest) = go (n-1) (')':acc) rest
    go n acc (c:rest)   = go n (c:acc) rest

-- | Pull the leading integer out of strings like "8u" or "(tUInt8)0u".
readWidth :: String -> Int
readWidth s = case reads (dropWhile (not . Char.isDigit) s) :: [(Int, String)] of
  [(n, _)] -> n
  _        -> 0

-- | Parse `init_symbol(&symbols[i], "NAME", KIND, &PTR[, WIDTH]);` lines.
parseInitSymbol :: Map.Map String Int -> String -> Maybe Sym
parseInitSymbol insts ln = case List.stripPrefix "init_symbol(" (dropWhile Char.isSpace ln) of
  Nothing -> Nothing
  Just rest ->
    let args = splitArgs rest
    in case args of
         [_, nameLit, kind, _, widthLit] | kind == "SYM_PORT" ->
           Just (SymPort (unquote nameLit) (readWidth widthLit))
         [_, nameLit, kind, ptr] | kind == "SYM_MODULE" ->
           let inst = drop (length ("&INST_" :: String)) ptr
           in case Map.lookup inst insts of
                Just w  -> Just (SymModule (unquote nameLit) w)
                Nothing -> Nothing
         _ -> Nothing

unquote :: String -> String
unquote s = case dropWhile Char.isSpace s of
  ('"':rest) -> takeWhile (/= '"') rest
  other      -> other

-- | Convert a bsc symbol name into a valid Haskell record field. Lowercases
-- the entire name: `EN_clear` -> `en_clear`, `count` -> `count`.
fieldName :: String -> String
fieldName "" = "_"
fieldName s  = map Char.toLower s

-- | Capitalize first letter: `mkCounter` -> `MkCounter` (module name).
capitalize :: String -> String
capitalize "" = ""
capitalize (c:cs) = Char.toUpper c : cs

renderModule :: String -> String -> [Sym] -> [Sym] -> String
renderModule modName moduleName ins outs = unlines $
  [ "{-# LANGUAGE DataKinds #-}"
  , "{-# LANGUAGE KindSignatures #-}"
  , "{-# LANGUAGE TypeApplications #-}"
  , "-- Generated by bscwave-gen-ports. Do not edit; regenerate after bsc."
  , "module " ++ moduleName
  , "  ( Inputs (..)"
  , "  , Outputs (..)"
  , "  , modelName"
  , "  ) where"
  , ""
  , "import Bscwave.Interface"
  , "import GHC.TypeLits (Nat)"
  , ""
  ] ++ recordDecl "Inputs"  ins  ++
  [ "" ] ++ recordDecl "Outputs" outs ++
  [ ""
  , instanceDecl "Inputs"  ins
  , ""
  , instanceDecl "Outputs" outs
  , ""
  , "modelName :: String"
  , "modelName = " ++ show modName
  ]

recordDecl :: String -> [Sym] -> [String]
recordDecl tyName syms =
  let entries = [(fieldName n, w) | s <- syms, let (n, w) = symPair s]
  in case entries of
       [] ->
         [ "data " ++ tyName ++ " (f :: Nat -> *) = " ++ tyName ]
       ((fn, fw):rest) ->
         [ "data " ++ tyName ++ " (f :: Nat -> *) = " ++ tyName
         , "  { " ++ fn ++ " :: f " ++ show fw
         ] ++
         [ "  , " ++ fn' ++ " :: f " ++ show fw' | (fn', fw') <- rest ] ++
         [ "  }" ]

instanceDecl :: String -> [Sym] -> String
instanceDecl tyName [] = unlines
  [ "instance Interface " ++ tyName ++ " where"
  , "  mkInterface _ = pure " ++ tyName
  , "  traverseI_ _ " ++ tyName ++ " = pure ()"
  ]
instanceDecl tyName syms = unlines
  [ "instance Interface " ++ tyName ++ " where"
  , "  mkInterface k = " ++ tyName ++ buildBody
  , "  traverseI_ f (" ++ tyName ++ " " ++ unwords vars ++ ") =" ++ traverseBody
  ]
  where
    bscNames = [n | s <- syms, let (n, _) = symPair s]
    widths   = [w | s <- syms, let (_, w) = symPair s]
    vars     = take (length syms) ["a" ++ show i | i <- [0 :: Int ..]]
    parts    = zipWith (\n w -> "k @" ++ show w ++ " " ++ show n) bscNames widths
    buildBody = case parts of
      []    -> ""
      (h:r) -> " <$> " ++ h ++ concatMap (" <*> " ++) r
    calls = zipWith (\n v -> "f " ++ show n ++ " " ++ v) bscNames vars
    traverseBody = case calls of
      []    -> " pure ()"
      (h:r) -> "\n    " ++ h ++ concatMap ("\n    *> " ++) r

symPair :: Sym -> (String, Int)
symPair (SymPort n w)   = (n, w)
symPair (SymModule n w) = (n, w)

main :: IO ()
main = do
  args <- getArgs
  (cxxPath, outPath) <- case args of
    [p]              -> pure (p, Nothing)
    [p, "-o", o]     -> pure (p, Just o)
    _ -> die "usage: bscwave-gen-ports <model>.cxx [-o Out.hs]"

  src <- readFile cxxPath
  let ls   = lines src
      insts = parseInsts ls
      syms  = [s | l <- ls, Just s <- [parseInitSymbol insts l]]
      ins   = [s | s@SymPort{}   <- syms]
      outs  = [s | s@SymModule{} <- syms]
      modName = takeBaseName cxxPath        -- "mkCounter"
      moduleName = capitalize modName       -- "MkCounter"
      rendered = renderModule modName moduleName ins outs

  case outPath of
    Nothing -> hPutStr stdout rendered
    Just o  -> withFile o WriteMode (`hPutStr` rendered)
