{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE TypeApplications #-}
-- Generated by bscwave-gen-ports. Do not edit; regenerate after bsc.
module MkCounter
  ( Inputs (..)
  , Outputs (..)
  , modelName
  ) where

import Bscwave.Interface
import GHC.TypeLits (Nat)

data Inputs (f :: Nat -> *) = Inputs
  { en_clear :: f 1
  , en_incr :: f 1
  }

data Outputs (f :: Nat -> *) = Outputs
  { count :: f 8
  }

instance Interface Inputs where
  mkInterface k = Inputs <$> k @1 "EN_clear" <*> k @1 "EN_incr"
  traverseI_ f (Inputs a0 a1) =
    f "EN_clear" a0
    *> f "EN_incr" a1


instance Interface Outputs where
  mkInterface k = Outputs <$> k @8 "count"
  traverseI_ f (Outputs a0) =
    f "count" a0


modelName :: String
modelName = "mkCounter"
